version: '2.0'
services:
  db:
    restart: on-failure
    image: mongo:3.2
    ports:
      - '27017:27017'
  web:
    restart: always
    build:
      context: .
    volumes:
      - ./:/app
    ports:
      - '8081:8081'
    depends_on:
      - db